# site settings
title: JD
subtitle: knowledgelib
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jakobdexl.github.io/"
author:
street_address:
city:
state:
zip_code:
country: Germany
permalink: /:categories/:title:output_ext


# homepage tiles
tiles-source: menu # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
git_address: https://github.com/JakobDexl/
github_username: JakobDexl
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
